#!/bin/sh /etc/rc.common

START=90
STOP=20

USE_PROCD=1

service_triggers() {
        procd_add_reload_trigger "noddos"
}

reload_service() {
	kill -SIGTERM $(cat /var/lib/noddos/noddos.pid)
}

start_service() {
  procd_open_instance
  procd_set_param command /usr/sbin/noddos -n -c /etc/noddos/noddos.conf

  # respawn automatically if something died, be careful if you have an
  # alternative process supervisor if process dies sooner than
  # respawn_threshold, it is considered crashed and after 5 retries the
  # service is stopped
  procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}

  procd_set_param file /etc/noddos/noddos.conf
  procd_set_param stdout 0 # forward stdout of the command to logd
  procd_set_param stderr 0 # same for stderr
  procd_set_param user root # run service as user nobody
  procd_close_instance
}

savematches_service() {
	kill -SIGUSR1 $(cat /var/lib/noddos/noddos.pid)
}

savedata_service() {
	kill -SIGUSR2 $(cat /var/lib/noddos/noddos.pid)
}

